basePath: /
definitions:
  agentHttpController.RequestData:
    properties:
      scriptContent:
        type: string
      url:
        type: string
      value:
        type: string
    type: object
host: localhost:9001
info:
  contact:
    email: support@swagger.io
    name: API Support
    url: http://www.swagger.io/support
  description: This is a sample server celler server.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: HellowWorldGoAgent API
  version: "1.0"
paths:
  /RunCommandByScriptContent:
    post:
      consumes:
      - application/json
      description: description
      parameters:
      - description: param for RunCommandByScriptContent
        in: body
        name: object
        required: true
        schema:
          $ref: '#/definitions/agentHttpController.RequestData'
      produces:
      - application/json
      responses:
        "201":
          description: The object was created successfully
          schema:
            type: string
        "400":
          description: Invalid request body
          schema:
            type: string
        "500":
          description: Failed to create object
          schema:
            type: string
      summary: Run command by script content
securityDefinitions:
  BasicAuth:
    type: basic
swagger: "2.0"
