definitions:
  agentHttpController.RequestDataForRunCommandByScriptContent:
    properties:
      scriptContent:
        default: |-
          #!/bin/bash
          echo "start"
          echo "hello yang"
          echo "end"
        type: string
    type: object
  agentHttpController.RequestDataForRunCommandByUrl:
    properties:
      url:
        default: https://ansys-gateway-development.s3.eu-west-3.amazonaws.com/first_script.sh
        type: string
    type: object
info:
  contact: {}
paths:
  /RunCommandByScriptContent:
    post:
      consumes:
      - application/json
      description: description
      parameters:
      - description: param for RunCommandByScriptContent
        in: body
        name: object
        required: true
        schema:
          $ref: '#/definitions/agentHttpController.RequestDataForRunCommandByScriptContent'
      produces:
      - application/json
      responses:
        "201":
          description: The object was created successfully
          schema:
            type: string
        "400":
          description: Invalid request body
          schema:
            type: string
        "500":
          description: Failed to create object
          schema:
            type: string
      summary: Run command using script content
  /RunCommandWithUrl:
    post:
      consumes:
      - application/json
      description: description
      parameters:
      - description: param for RunCommandWithUrl
        in: body
        name: object
        required: true
        schema:
          $ref: '#/definitions/agentHttpController.RequestDataForRunCommandByUrl'
      produces:
      - application/json
      responses:
        "201":
          description: The object was created successfully
          schema:
            type: string
        "400":
          description: Invalid request body
          schema:
            type: string
        "500":
          description: Failed to create object
          schema:
            type: string
      summary: Run command using url
swagger: "2.0"
